### ISSUE TITLE
Full example front end entry form

### ISSUE THREAD

**Issue by arifje** [fruitstudios/craft-uploadit#3]
Cool plugin, but the docs are very unclear. Would be nice if we could get a complete example on how to use this in the front end entry form. I need to upload a video in this form.

Thanks!

Edit; also, I am getting an error when using the example from the docs;

```
Neither the property "uploader" nor one of the methods "uploader()", "getuploader()"/"isuploader()"/"hasuploader()" or "__call()" exist and have public access in class "fruitstudios\uploadit\variables\UploaditVariable".
```

**Comment by samhibberd** [comment]
It's coming soon, we ran into some issues which we are working through which should be completed, along with the docs over the next week!

**Comment by loshose** [comment]
Also tried to use this plugin and came across this same error. Any progress?

**Comment by samhibberd** [comment]
Hey @loshose, we ran into some issues (profile image uploader, temporary uploads for new entries) which needed to be fixed ready for a site launch a couple of weeks ago. I'm now back in the office after a couple of weeks leave and we will really try to get a release ready for the plugin store.

**Comment by j2is** [comment]
Hey Sam, great plugin would love to use, did you have a chance to fix these issues?

**Comment by samhibberd** [comment]
@j2is both have been fixed yes, we just haven't had time to fully test the javascript or write docs. We are using it in production on a handful of sites. You are welcome to have a play with the latest stable version which is available on packagist (fruitstudios/uploadit).

Be great to hear any feedback, bugs etc etc.

Disclaimer - This is a pre release version, backup backup backup and we can't really offer support until its officially released.

**Comment by jacobgraf** [comment]
Any updates on this? We'd love to use it but are also getting the same error.

**Comment by samhibberd** [comment]
@jacobgraf this is high on our list and we would love to get it out there, really hoping there will some dev resource available really soon! 

For now 1.0.9 is the latest version, which we are using in production, if you want to test it out, go for it, with the disclaimer please backup backup backup. 

Here are a couple of example usage snippets for 1.0.9:

https://github.com/fruitstudios/craft-uploadit/wiki/Examples-(Beta-1.0.9)
