### ISSUE TITLE
Release status?

### ISSUE THREAD

**Issue by mark-adigital** [fruitstudios/craft-uploadit#4]
Hi,

I was just wondering what the status of this plugin is? I can't seem to find it on the plugin store, but see from the readme that the plan was for it to be a paid plugin with the store's launch.

Thanks,

Mark

**Comment by shornuk** [comment]
Hi @mark-adigital , still being worked on at the moment. Hoping to release in the not-to-distant future! Sorry, can't give a firm date.

Thanks,
